"""Create initial tables

Revision ID: 08af0fac1fc0
Revises: 58a4db083ced
Create Date: 2025-06-17 14:11:30.523246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08af0fac1fc0'
down_revision = '58a4db083ced'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
