"""Create initial tables

Revision ID: 58a4db083ced
Revises: a875aa2a8fe2
Create Date: 2025-06-17 13:06:03.456240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a4db083ced'
down_revision = 'a875aa2a8fe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
