"""Create initial tables

Revision ID: a76bd911c7b3
Revises: 08af0fac1fc0
Create Date: 2025-06-18 07:27:27.228046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76bd911c7b3'
down_revision = '08af0fac1fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
