"""Create initial tables

Revision ID: a875aa2a8fe2
Revises: fe8cabecb69f
Create Date: 2025-06-17 12:38:55.623487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a875aa2a8fe2'
down_revision = 'fe8cabecb69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
