"""Create initial tables

Revision ID: fe8cabecb69f
Revises: 
Create Date: 2025-06-17 10:04:24.978846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8cabecb69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id_card_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_number'), 'clients', ['client_number'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CHARGE_CLIENTELE', 'ANALYSTE_PRETS', 'ADMINISTRATEUR_PRETS', 'CHARGE_REMBOURSEMENT', 'DIRECTEUR_AGENCE', 'READONLY', name='userrole'), nullable=False),
    sa.Column('agency', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('loan_type', sa.Enum('CLASSIC_ACQUIRER', 'CLASSIC_BUILDER', 'RENTAL_ORDINARY', 'YOUNG_LAND', name='loantype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'IN_PROGRESS', 'DISBURSING', 'COMPLETED', 'CANCELLED', 'SUSPENDED', name='loanstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('grace_period_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mortgage_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('property_title_number', sa.String(length=100), nullable=True),
    sa.Column('property_location', sa.Text(), nullable=True),
    sa.Column('life_insurance_company', sa.String(length=100), nullable=True),
    sa.Column('fire_insurance_company', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_number'), 'loans', ['loan_number'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('VALIDITY_WARNING', 'VALIDITY_CRITICAL', 'WORK_DELAY_WARNING', 'WORK_DELAY_CRITICAL', 'REPAYMENT_UPCOMING', 'REPAYMENT_IMMINENT', 'MISSING_DOCUMENT', 'DOCUMENT_EXPIRY', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'RESOLVED', 'ESCALATED', name='alertstatus'), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('disbursement_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'SUSPENDED', name='disbursementstatus'), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('disbursed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('work_completion_percentage', sa.Integer(), nullable=True),
    sa.Column('site_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_visit_report', sa.Text(), nullable=True),
    sa.Column('bet_name', sa.String(length=200), nullable=True),
    sa.Column('bet_report_received', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursements_id'), 'disbursements', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('disbursement_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('DEMANDE_MANUSCRITE', 'CNI', 'CERTIFICAT_PROPRIETE', 'PLAN_LOCALISATION', 'CASIER_JUDICIAIRE', 'FACTURE_ENEO', 'CONTRAT_PRET', 'NOTIFICATION_ACCORD', 'CONVENTION_SIGNEE', 'DEMANDE_DEBLOCAGE', 'RAPPORT_VISITE', 'RAPPORT_BET', 'BIA_DGE', 'BIA_INCENDIE', 'BIA_TRC', 'AUTRES', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursements.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_disbursements_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_loans_loan_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
